# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [1]:
import pandas as pd
import numpy as np
import time
df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")
# Printing the whole dataset for reference
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Part 1: Data Exploration ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

In [40]:
#1. Print the shape and column names of the dataset.
# Prints the shape of the dataframe.
print("1. Print the shape and column names of the dataset.")
df.shape

# Prints column names of the dataset
# print(df.head())
df.columns

1. Print the shape and column names of the dataset.

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [41]:
# 2. Display basic information and summary statistics about the dataset.
# Display basic information and summary statistics. Used https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html to figure out function to use.
print("2. Display basic information and summary statistics about the dataset.")
df.describe()
# df.describe()

2. Display basic information and summary statistics about the dataset.

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [42]:
# 3. Show the first 10 rows.
print("3. Show the first 10 rows.")
# Using loc to print rows as per Lab 1's video. Using indexes 0 to 9 due to indexing starting at 0.
df.loc[0:9]

3. Show the first 10 rows.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### Part 2: Indexing and Selection ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

In [47]:
# "1. Select the names column."
print("1. Select the names column.")

df[['Name']]

1. Select the names column.

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                        Graham, Miss Margaret Edith
888            Johnston, Miss Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

In [59]:
# "2. Select multiple columns of your choice."
print("2. Select multiple columns of your choice.")

# Using iloc to print out multiple columns without specifically declaring column names
# Used https://stackoverflow.com/questions/11285613/selecting-multiple-columns-in-a-pandas-dataframe as a guide
df[['Sex', 'Age']]

2. Select multiple columns of your choice.

        Sex   Age
0      male  22.0
1    female  38.0
2    female  26.0
3    female  35.0
4      male  35.0
..      ...   ...
886    male  27.0
887  female  19.0
888  female   NaN
889    male  26.0
890    male  32.0

[891 rows x 2 columns]

In [14]:
# 3. Select a single row from the dataset.
# Chosen for recreating with pure Python; time-tracking code is included but commented out since keeping it in seem to not print the DataFrame
# start = time.time()
print("3. Select a single row from the dataset.")

df.loc[[0]]
# end = time.time()
# print(f"Time of {end - start}")

3. Select a single row from the dataset.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Euros
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S,6.235

In [54]:
# 4. Select a rectangular section (subset of rows and columns).
print("4. Select a rectangular section (subset of rows and columns).")

df.loc[[0, 1], ['Survived', 'Pclass', 'Name', 'Age']]

   Survived  Pclass                                               Name   Age
0         0       3                            Braund, Mr. Owen Harris  22.0
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0

### Part 3: Filtering ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

In [15]:
# 1. Show only the rows where the age is above 60.
# Chosen for recreating with pure Python; time-tracking code is included but commented out since keeping it in seem to not print the DataFrame
# start = time.time()
print("1. Show only the rows where the age is above 60.") 

abovesixtydf = df[df['Age'] > 60]
abovesixtydf
# end = time.time()
# print(f"Time of {end - start}")

1. Show only the rows where the age is above 60.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Euros
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S,9.030000
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C,53.302112
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C,29.802612
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q,6.665000
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S,28.810000
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S,22.833000
275,276,1,1,"Andrews, Miss Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,67.044138
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q,6.665000
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S,5.364250
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,226.180000
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S,22.833000
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,8.245250
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,42.573612
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S,22.360000
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S,22.833000
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S,9.030000
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S,27.795888
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S,25.800000
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S,9.030000
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S,61.060000
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN,68.800000
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S,6.686500

In [69]:
# 2. Show rows where the fare is above 100 and the passenger was in 1st class.
print("2. Show rows where the fare is above 100 and the passenger was in 1st class.")

# 1st class appears to be represented by "1" in Pclass
highfarefirstclassdf = df[(df['Fare'] > 100) & (df['Pclass'] == 1)]
highfarefirstclassdf

2. Show rows where the fare is above 100 and the passenger was in 1st class.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

In [78]:
# 3. Identify and isolate rows with missing values in the age column.
print("3. Identify and isolate rows with missing values in the age column.")

# Using the isnull() function to detect NaN (missing) values
# Found using https://note.nkmk.me/en/python-pandas-nan-extract/#google_vignette
missingagesdf = df[(df['Age'].isnull())]
missingagesdf

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Part 4: Reindexing and Dropping ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

In [109]:
# 1. Reverse the row order of the dataset.
print("# 1. Reverse the row order of the dataset.")

# The rows are numerical in ascending order. Great, I'll just need to put it in descending order, then
# Figured it's good practice to make a copy of df so I'm not changing it and having those changes carry over when next I reference df and beyond
reversedf = df

# Value for by seems to be arbitrary so long as it names a column
# Adapted from https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html
# ascending=False sorts the values in descending order
reversedf.sort_values(by="PassengerId", ascending=False)

# 1. Reverse the row order of the dataset.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Euros
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,6.665000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,25.800000
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,20.167000
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,25.800000
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,11.180000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000

In [93]:
# 2. Remove one column from the dataset.
print("2. Remove one column from the dataset.")

removedonedf = df
removedonedf.drop('Pclass', axis=1)

2. Remove one column from the dataset.

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [92]:
# 3. Remove all rows with missing values in the age column.
print("3. Remove all rows with missing values in the age column.")

# Figured it's good practice to make a copy of df so I'm not changing it and having those changes carry over when next I reference df and beyond
removedmissingagesdf = df
# Using notnull() means that the rows with missing age values are not included
# Uses Boolean Indexing as outlined in Pandas.ipynb
# notnull() usage adapted from https://pandas.pydata.org/docs/reference/api/pandas.notnull.html
removedmissingagesdf = df[(df['Age'].notnull())]
removedmissingagesdf

3. Remove all rows with missing values in the age column.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Part 5: Arithmetic and Data Alignment ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

In [16]:
# 1. Create a new column that converts fares from USD to Euros.
# Chosen for recreating with pure Python; time-tracking code is included but commented out since keeping it in seem to not print the DataFrame
# start = time.time()
print("1. Create a new column that converts fares from USD to Euros.")

toeurosdf = df
# As of May 16, 3:21 a.m, The conversion from USD to Euros is 1 USD = 0.86 Euro.
# https://pandas.pydata.org/docs/getting_started/intro_tutorials/05_add_columns.html has shown me that I can add a new column without reindex()
toeurosdf["Euros"] = toeurosdf["Fare"] * 0.86
toeurosdf
# end = time.time()
# print(f"Time of {end - start}")

1. Create a new column that converts fares from USD to Euros.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Euros
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,11.180000
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,25.800000
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,20.167000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,25.800000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,6.665000

In [66]:
# 2. Subtract the average age from every age value.
print("2. Subtract the average age from every age value.")

agecolumndf=df["Age"]
meanage = agecolumndf.mean()
meanagegonedf = df["Age"] - meanage
meanagegonedf

2. Subtract the average age from every age value.

0      -7.699118
1       8.300882
2      -3.699118
3       5.300882
4       5.300882
         ...
886    -2.699118
887   -10.699118
888          NaN
889    -3.699118
890     2.300882
Name: Age, Length: 891, dtype: float64

In [83]:
# 3. Subtract a custom array from two selected columns in the dataset.
print("3. Subtract a custom array from two selected columns in the dataset.")

# Custom array should subtract 1 from every Age value and 2 from every SibSp value
custom_array = pd.DataFrame({'Age': [1], 'SibSp': [2]})
subtracted_df = df[['Age', 'SibSp']]

# As in Panda.ipynb, use fill_value as a safeguard against empty values
subtracted_df.sub(custom_array, fill_value=0)

3. Subtract a custom array from two selected columns in the dataset.

      Age  SibSp
0    21.0   -1.0
1    38.0    1.0
2    26.0    0.0
3    35.0    1.0
4    35.0    0.0
..    ...    ...
886  27.0    0.0
887  19.0    0.0
888   NaN    1.0
889  26.0    0.0
890  32.0    0.0

[891 rows x 2 columns]

### Part 6: Applying Functions ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

In [134]:
# 1. Create a new column with the number of characters in each name.

# The question does not specify if we have to exclude commas; this implementation will consider them as characters

# Define all columns, adding 'Age Category' to the mix.
new_col = ['PassengerId', 'Survived', 'Pclass', 'Name',	'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'NameChars']

# By starting with_age_category as a copy of df, we can print out the whole datasheet with the new Age Category column, not just that column.
with_namechars_category = df.reindex(columns=new_col)

# Apparently Pandas has Series.str.len() which can be used here instead of defining an entirely new function for finding string length.
# Adapted from https://stackoverflow.com/a/62629944
# Only the Name column will have its string length checked.
with_namechars_category['NameChars'] = df['Name'].str.len()
with_namechars_category

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,NameChars
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,23
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,51
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,21
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,44
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,21
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,27
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,39
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,21
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,19

In [120]:
# 2. Calculate the difference between fare and age for each row.

# Uses sub() from Pandas.ipynb, implementation adapted from 
# https://www.geeksforgeeks.org/python/difference-of-two-columns-in-pandas-dataframe/https://www.geeksforgeeks.org/python/difference-of-two-columns-in-pandas-dataframe/

# We just need to use the sub() method to subtract both columns from each other, then store them in another column, "difference"
# Using fill_value for safety as outlined in Pandas.ipynb; noticed that without this, a row with "NaN" will resule in a result of NaN
final_df['difference'] = df['Fare'].sub(df['Age'],fill_value=0, axis = 0)
final_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,difference
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,-14.7500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,33.2833
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,-18.0750
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,18.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,-26.9500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,-14.0000
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,11.0000
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,4.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,-24.2500

In [139]:
#### 3. Round all numerical values in the dataset to one decimal place.
# incomplete
def round_numerical(x):
    # Using numpy's round function, since we can!
    number = np.round(x,1)
    return number
    
new_col = ['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

df_characters = df.reindex(columns=new_col)

# Let's get only the columns in df that are numerical.
df_characters = df_characters.apply(round_numerical, axis=1)
df_characters

     PassengerId  Survived  Pclass   Age  SibSp  Parch  Fare
0            1.0       0.0     3.0  22.0    1.0    0.0   7.2
1            2.0       1.0     1.0  38.0    1.0    0.0  71.3
2            3.0       1.0     3.0  26.0    0.0    0.0   7.9
3            4.0       1.0     1.0  35.0    1.0    0.0  53.1
4            5.0       0.0     3.0  35.0    0.0    0.0   8.0
..           ...       ...     ...   ...    ...    ...   ...
886        887.0       0.0     2.0  27.0    0.0    0.0  13.0
887        888.0       1.0     1.0  19.0    0.0    0.0  30.0
888        889.0       0.0     3.0   NaN    1.0    2.0  23.4
889        890.0       1.0     1.0  26.0    0.0    0.0  30.0
890        891.0       0.0     3.0  32.0    0.0    0.0   7.8

[891 rows x 7 columns]

### Part 7: Mapping and Transformation ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

In [46]:
#1. Convert categorical values in the gender column to numeric codes.
print("1. Convert categorical values in the gender column to numeric codes.")

def sex_categories(x):
    if(x == 'male'):
        return 0
    elif(x == 'female'):
        return 1
    else: # If input is something else, account for it with NaN
        return np.nan

stringgender = df[['Sex']]
# 0 = 'male', otherwise 1.
numericgender = stringgender.map(sex_categories)
numericgender

1. Convert categorical values in the gender column to numeric codes.

     Sex
0      0
1      1
2      1
3      1
4      0
..   ...
886    0
887    1
888    1
889    0
890    0

[891 rows x 1 columns]

In [44]:
#2. Create a new column that categorizes age into groups (e.g., child, adult, senior).
print("2. Create a new column that categorizes age into groups (e.g., child, adult, senior).")

def age_categories(x):
    if(x >=65):
        return 'Senior'
    elif(x >= 19):
        return 'Adult'
    elif(x >= 0):
        return 'Child'
    else: # Some inputs are NaN; this will account for that.
        return np.nan

ages = df[['Age']]

# Define all columns, adding 'Age Category' to the mix.
new_col = ['PassengerId', 'Survived', 'Pclass', 'Name',	'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Age Category']

# By starting with_age_category as a copy of df, we can print out the whole datasheet with the new Age Category column, not just that column.
with_age_category = df.reindex(columns=new_col)

# agecategory = with_age_category[['Age Category']]

# Age Category will start as a copy of Age's values.
with_age_category['Age Category'] = with_age_category[['Age']]

#Then, send with_age_category only to the age_categories function.
with_age_category['Age Category'] = with_age_category['Age Category'].map(age_categories)

with_age_category

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age Category
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult

### Part 8: Python Time

"This lab task also includes Part 8, where you can freely choose one task from each of Parts 2, 3, or 5 (3 tasks in total). Try to solve that chosen task without using Pandas, only with pure Python code. For this, convert the CSV dataset into a list (or any other native Python data type) and implement the task without using any external libraries. Then, compare the execution time of both versions (with Pandas and without it)."

### Selecting Tasks:
#2, Select a single row from the dataset.
#3, Show only the rows where the age is above 60.
#5, Create a new column that converts fares from USD to Euros.

In [2]:
# DEFINITION OF LIST FOR ALL SUBSEQUENT ANSWERS

# Found that pandas has a function to convert a DataFrame to a list through https://stackoverflow.com/a/70222228
# Beyond this, it's going to be pure Python
l = df.values.tolist()

In [17]:
#2, Select a single row from the dataset.
# start= time.time()
print("#2, Select a single row from the dataset.")

print(l[0])

# end = time.time()
# print(f"Time of {end - start}")

#2, Select a single row from the dataset.
[1, 0, 3, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0, 'A/5 21171', 7.25, nan, 'S', 6.235]

In [23]:
#3, Show only the rows where the age is above 60.
# start= time.time()
print("#3, Show only the rows where the age is above 60.")

rowsAboveSixty = []
#Age is the sixth element in a single row; it is index 5.
def find_rows_above_sixty(x):
    for x in l:
        if(x[5] > 60):
            rowsAboveSixty.append(x)

find_rows_above_sixty(l)
print(rowsAboveSixty)

# end = time.time()
# print(f"Time of {end - start}")

#3, Show only the rows where the age is above 60.
[[34, 0, 2, 'Wheadon, Mr. Edward H', 'male', 66.0, 0, 0, 'C.A. 24579', 10.5, nan, 'S', 9.03, 9.03, 9.03], [55, 0, 1, 'Ostby, Mr. Engelhart Cornelius', 'male', 65.0, 0, 1, '113509', 61.9792, 'B30', 'C', 53.302112, 53.302112, 53.302112], [97, 0, 1, 'Goldschmidt, Mr. George B', 'male', 71.0, 0, 0, 'PC 17754', 34.6542, 'A5', 'C', 29.802612000000003, 29.802612000000003, 29.802612000000003], [117, 0, 3, 'Connors, Mr. Patrick', 'male', 70.5, 0, 0, '370369', 7.75, nan, 'Q', 6.665, 6.665, 6.665], [171, 0, 1, 'Van der hoef, Mr. Wyckoff', 'male', 61.0, 0, 0, '111240', 33.5, 'B19', 'S', 28.81, 28.81, 28.81], [253, 0, 1, 'Stead, Mr. William Thomas', 'male', 62.0, 0, 0, '113514', 26.55, 'C87', 'S', 22.833000000000002, 22.833000000000002, 22.833000000000002], [276, 1, 1, 'Andrews, Miss Kornelia Theodosia', 'female', 63.0, 1, 0, '13502', 77.9583, 'D7', 'S', 67.04413799999999, 67.04413799999999, 67.04413799999999], [281, 0, 3, 'Duane, Mr. Frank', 'male', 65.0, 0, 0, '336439', 7.75, nan, 'Q', 6.665, 6.665, 6.665], [327, 0, 3, 'Nysveen, Mr. Johan Hansen', 'male', 61.0, 0, 0, '345364', 6.2375, nan, 'S', 5.36425, 5.36425, 5.36425], [439, 0, 1, 'Fortune, Mr. Mark', 'male', 64.0, 1, 4, '19950', 263.0, 'C23 C25 C27', 'S', 226.18, 226.18, 226.18], [457, 0, 1, 'Millet, Mr. Francis Davis', 'male', 65.0, 0, 0, '13509', 26.55, 'E38', 'S', 22.833000000000002, 22.833000000000002, 22.833000000000002], [484, 1, 3, 'Turkula, Mrs. (Hedwig)', 'female', 63.0, 0, 0, '4134', 9.5875, nan, 'S', 8.24525, 8.24525, 8.24525], [494, 0, 1, 'Artagaveytia, Mr. Ramon', 'male', 71.0, 0, 0, 'PC 17609', 49.5042, nan, 'C', 42.573612, 42.573612, 42.573612], [546, 0, 1, 'Nicholson, Mr. Arthur Ernest', 'male', 64.0, 0, 0, '693', 26.0, nan, 'S', 22.36, 22.36, 22.36], [556, 0, 1, 'Wright, Mr. George', 'male', 62.0, 0, 0, '113807', 26.55, nan, 'S', 22.833000000000002, 22.833000000000002, 22.833000000000002], [571, 1, 2, 'Harris, Mr. George', 'male', 62.0, 0, 0, 'S.W./PP 752', 10.5, nan, 'S', 9.03, 9.03, 9.03], [626, 0, 1, 'Sutton, Mr. Frederick', 'male', 61.0, 0, 0, '36963', 32.3208, 'D50', 'S', 27.795887999999998, 27.795887999999998, 27.795887999999998], [631, 1, 1, 'Barkworth, Mr. Algernon Henry Wilson', 'male', 80.0, 0, 0, '27042', 30.0, 'A23', 'S', 25.8, 25.8, 25.8], [673, 0, 2, 'Mitchell, Mr. Henry Michael', 'male', 70.0, 0, 0, 'C.A. 24580', 10.5, nan, 'S', 9.03, 9.03, 9.03], [746, 0, 1, 'Crosby, Capt. Edward Gifford', 'male', 70.0, 1, 1, 'WE/P 5735', 71.0, 'B22', 'S', 61.06, 61.06, 61.06], [830, 1, 1, 'Stone, Mrs. George Nelson (Martha Evelyn)', 'female', 62.0, 0, 0, '113572', 80.0, 'B28', nan, 68.8, 68.8, 68.8], [852, 0, 3, 'Svensson, Mr. Johan', 'male', 74.0, 0, 0, '347060', 7.775, nan, 'S', 6.6865000000000006, 6.6865000000000006, 6.6865000000000006]]

In [3]:
#5, Create a new column that converts fares from USD to Euros.

# start= time.time()
columnOfEuros = []

# Make a copy of l so that new stuff doesn't keep appending to the list during subsequent runs.
#Fare is the tenth element in a single row; it is index 9.
def calculate_euros(x):
    for x in newl:
        # As of May 16, 3:21 a.m, The conversion from USD to Euros is 1 USD = 0.86 Euro.
        columnOfEuros.append(x[9] * 0.86)

def append_euros(euro):
    counter = 0
    for x in newl:
        x.append(euro[counter])
        counter = counter + 1
    print(newl)

newl = l
# Get the Euro values, this will be an array in the same order as the list.
calculate_euros(newl)
# Now append them to each row of the dataset.
append_euros(columnOfEuros)
# Even though newl gets deleted, how come reruns still keep on appending values to each row?
del newl

# end = time.time()
# print(f"Time of {end - start}")

[[1, 0, 3, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0, 'A/5 21171', 7.25, nan, 'S', 6.235], [2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'female', 38.0, 1, 0, 'PC 17599', 71.2833, 'C85', 'C', 61.303638], [3, 1, 3, 'Heikkinen, Miss Laina', 'female', 26.0, 0, 0, 'STON/O2. 3101282', 7.925, nan, 'S', 6.8155], [4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female', 35.0, 1, 0, '113803', 53.1, 'C123', 'S', 45.666000000000004], [5, 0, 3, 'Allen, Mr. William Henry', 'male', 35.0, 0, 0, '373450', 8.05, nan, 'S', 6.923000000000001], [6, 0, 3, 'Moran, Mr. James', 'male', nan, 0, 0, '330877', 8.4583, nan, 'Q', 7.274138], [7, 0, 1, 'McCarthy, Mr. Timothy J', 'male', 54.0, 0, 0, '17463', 51.8625, 'E46', 'S', 44.601749999999996], [8, 0, 3, 'Palsson, Master Gosta Leonard', 'male', 2.0, 3, 1, '349909', 21.075, nan, 'S', 18.124499999999998], [9, 1, 3, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'female', 27.0, 0, 2, '347742', 11.1333, nan, 'S', 9.574638], [10, 1, 2, 'Nasser, Mrs. Nicholas (Adele Achem)', 'female', 14.0, 1, 0, '237736', 30.0708, nan, 'C', 25.860888], [11, 1, 3, 'Sandstrom, Miss Marguerite Rut', 'female', 4.0, 1, 1, 'PP 9549', 16.7, 'G6', 'S', 14.361999999999998], [12, 1, 1, 'Bonnell, Miss Elizabeth', 'female', 58.0, 0, 0, '113783', 26.55, 'C103', 'S', 22.833000000000002], [13, 0, 3, 'Saundercock, Mr. William Henry', 'male', 20.0, 0, 0, 'A/5. 2151', 8.05, nan, 'S', 6.923000000000001], [14, 0, 3, 'Andersson, Mr. Anders Johan', 'male', 39.0, 1, 5, '347082', 31.275, nan, 'S', 26.8965], [15, 0, 3, 'Vestrom, Miss Hulda Amanda Adolfina', 'female', 14.0, 0, 0, '350406', 7.8542, nan, 'S', 6.754612], [16, 1, 2, 'Hewlett, Mrs. (Mary D Kingcome) ', 'female', 55.0, 0, 0, '248706', 16.0, nan, 'S', 13.76], [17, 0, 3, 'Rice, Master Eugene', 'male', 2.0, 4, 1, '382652', 29.125, nan, 'Q', 25.0475], [18, 1, 2, 'Williams, Mr. Charles Eugene', 'male', nan, 0, 0, '244373', 13.0, nan, 'S', 11.18], [19, 0, 3, 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 'female', 31.0, 1, 0, '345763', 18.0, nan, 'S', 15.48], [20, 1, 3, 'Masselmani, Mrs. Fatima', 'female', nan, 0, 0, '2649', 7.225, nan, 'C', 6.2135], [21, 0, 2, 'Fynney, Mr. Joseph J', 'male', 35.0, 0, 0, '239865', 26.0, nan, 'S', 22.36], [22, 1, 2, 'Beesley, Mr. Lawrence', 'male', 34.0, 0, 0, '248698', 13.0, 'D56', 'S', 11.18], [23, 1, 3, 'McGowan, Miss Anna "Annie"', 'female', 15.0, 0, 0, '330923', 8.0292, nan, 'Q', 6.905111999999999], [24, 1, 1, 'Sloper, Mr. William Thompson', 'male', 28.0, 0, 0, '113788', 35.5, 'A6', 'S', 30.53], [25, 0, 3, 'Palsson, Miss Torborg Danira', 'female', 8.0, 3, 1, '349909', 21.075, nan, 'S', 18.124499999999998], [26, 1, 3, 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 'female', 38.0, 1, 5, '347077', 31.3875, nan, 'S', 26.99325], [27, 0, 3, 'Emir, Mr. Farred Chehab', 'male', nan, 0, 0, '2631', 7.225, nan, 'C', 6.2135], [28, 0, 1, 'Fortune, Mr. Charles Alexander', 'male', 19.0, 3, 2, '19950', 263.0, 'C23 C25 C27', 'S', 226.18], [29, 1, 3, 'O\'Dwyer, Miss Ellen "Nellie"', 'female', nan, 0, 0, '330959', 7.8792, nan, 'Q', 6.7761119999999995], [30, 0, 3, 'Todoroff, Mr. Lalio', 'male', nan, 0, 0, '349216', 7.8958, nan, 'S', 6.790388], [31, 0, 1, 'Uruchurtu, Don. Manuel E', 'male', 40.0, 0, 0, 'PC 17601', 27.7208, nan, 'C', 23.839888], [32, 1, 1, 'Spencer, Mrs. William Augustus (Marie Eugenie)', 'female', nan, 1, 0, 'PC 17569', 146.5208, 'B78', 'C', 126.00788800000001], [33, 1, 3, 'Glynn, Miss Mary Agatha', 'female', nan, 0, 0, '335677', 7.75, nan, 'Q', 6.665], [34, 0, 2, 'Wheadon, Mr. Edward H', 'male', 66.0, 0, 0, 'C.A. 24579', 10.5, nan, 'S', 9.03], [35, 0, 1, 'Meyer, Mr. Edgar Joseph', 'male', 28.0, 1, 0, 'PC 17604', 82.1708, nan, 'C', 70.666888], [36, 0, 1, 'Holverson, Mr. Alexander Oskar', 'male', 42.0, 1, 0, '113789', 52.0, nan, 'S', 44.72], [37, 1, 3, 'Mamee, Mr. Hanna', 'male', nan, 0, 0, '2677', 7.2292, nan, 'C', 6.217111999999999], [38, 0, 3, 'Cann, Mr. Ernest Charles', 'male', 21.0, 0, 0, 'A./5. 2152', 8.05, nan, 'S', 6.923000000000001], [39, 0, 3, 'Vander Planke, Miss Augusta Maria', 'female', 18.0, 2, 0, '345764', 18.0, nan, 'S', 15.48], [40, 1, 3, 'Nicola-Yarred, Miss Jamila', 'female', 14.0, 1, 0, '2651', 11.2417, nan, 'C', 9.667862], [41, 0, 3, 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 'female', 40.0, 1, 0, '7546', 9.475, nan, 'S', 8.1485], [42, 0, 2, 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 'female', 27.0, 1, 0, '11668', 21.0, nan, 'S', 18.06], [43, 0, 3, 'Kraeff, Mr. Theodor', 'male', nan, 0, 0, '349253', 7.8958, nan, 'C', 6.790388], [44, 1, 2, 'Laroche, Miss Simonne Marie Anne Andree', 'female', 3.0, 1, 2, 'SC/Paris 2123', 41.5792, nan, 'C', 35.758112], [45, 1, 3, 'Devaney, Miss Margaret Delia', 'female', 19.0, 0, 0, '330958', 7.8792, nan, 'Q', 6.7761119999999995], [46, 0, 3, 'Rogers, Mr. William John', 'male', nan, 0, 0, 'S.C./A.4. 23567', 8.05, nan, 'S', 6.923000000000001], [47, 0, 3, 'Lennon, Mr. Denis', 'male', nan, 1, 0, '370371', 15.5, nan, 'Q', 13.33], [48, 1, 3, "O'Driscoll, Miss Bridget", 'female', nan, 0, 0, '14311', 7.75, nan, 'Q', 6.665], [49, 0, 3, 'Samaan, Mr. Youssef', 'male', nan, 2, 0, '2662', 21.6792, nan, 'C', 18.644112], [50, 0, 3, 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 'female', 18.0, 1, 0, '349237', 17.8, nan, 'S', 15.308], [51, 0, 3, 'Panula, Master Juha Niilo', 'male', 7.0, 4, 1, '3101295', 39.6875, nan, 'S', 34.13125], [52, 0, 3, 'Nosworthy, Mr. Richard Cater', 'male', 21.0, 0, 0, 'A/4. 39886', 7.8, nan, 'S', 6.708], [53, 1, 1, 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'female', 49.0, 1, 0, 'PC 17572', 76.7292, 'D33', 'C', 65.98711200000001], [54, 1, 2, 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 'female', 29.0, 1, 0, '2926', 26.0, nan, 'S', 22.36], [55, 0, 1, 'Ostby, Mr. Engelhart Cornelius', 'male', 65.0, 0, 1, '113509', 61.9792, 'B30', 'C', 53.302112], [56, 1, 1, 'Woolner, Mr. Hugh', 'male', nan, 0, 0, '19947', 35.5, 'C52', 'S', 30.53], [57, 1, 2, 'Rugg, Miss Emily', 'female', 21.0, 0, 0, 'C.A. 31026', 10.5, nan, 'S', 9.03], [58, 0, 3, 'Novel, Mr. Mansouer', 'male', 28.5, 0, 0, '2697', 7.2292, nan, 'C', 6.217111999999999], [59, 1, 2, 'West, Miss Constance Mirium', 'female', 5.0, 1, 2, 'C.A. 34651', 27.75, nan, 'S', 23.865], [60, 0, 3, 'Goodwin, Master William Frederick', 'male', 11.0, 5, 2, 'CA 2144', 46.9, nan, 'S', 40.333999999999996], [61, 0, 3, 'Sirayanian, Mr. Orsen', 'male', 22.0, 0, 0, '2669', 7.2292, nan, 'C', 6.217111999999999], [62, 1, 1, 'Icard, Miss Amelie', 'female', 38.0, 0, 0, '113572', 80.0, 'B28', nan, 68.8], [63, 0, 1, 'Harris, Mr. Henry Birkhardt', 'male', 45.0, 1, 0, '36973', 83.475, 'C83', 'S', 71.7885], [64, 0, 3, 'Skoog, Master Harald', 'male', 4.0, 3, 2, '347088', 27.9, nan, 'S', 23.994], [65, 0, 1, 'Stewart, Mr. Albert A', 'male', nan, 0, 0, 'PC 17605', 27.7208, nan, 'C', 23.839888], [66, 1, 3, 'Moubarek, Master Gerios', 'male', nan, 1, 1, '2661', 15.2458, nan, 'C', 13.111388], [67, 1, 2, 'Nye, Mrs. (Elizabeth Ramell)', 'female', 29.0, 0, 0, 'C.A. 29395', 10.5, 'F33', 'S', 9.03], [68, 0, 3, 'Crease, Mr. Ernest James', 'male', 19.0, 0, 0, 'S.P. 3464', 8.1583, nan, 'S', 7.016138000000001], [69, 1, 3, 'Andersson, Miss Erna Alexandra', 'female', 17.0, 4, 2, '3101281', 7.925, nan, 'S', 6.8155], [70, 0, 3, 'Kink, Mr. Vincenz', 'male', 26.0, 2, 0, '315151', 8.6625, nan, 'S', 7.44975], [71, 0, 2, 'Jenkin, Mr. Stephen Curnow', 'male', 32.0, 0, 0, 'C.A. 33111', 10.5, nan, 'S', 9.03], [72, 0, 3, 'Goodwin, Miss Lillian Amy', 'female', 16.0, 5, 2, 'CA 2144', 46.9, nan, 'S', 40.333999999999996], [73, 0, 2, 'Hood, Mr. Ambrose Jr', 'male', 21.0, 0, 0, 'S.O.C. 14879', 73.5, nan, 'S', 63.21], [74, 0, 3, 'Chronopoulos, Mr. Apostolos', 'male', 26.0, 1, 0, '2680', 14.4542, nan, 'C', 12.430612], [75, 1, 3, 'Bing, Mr. Lee', 'male', 32.0, 0, 0, '1601', 56.4958, nan, 'S', 48.586388], [76, 0, 3, 'Moen, Mr. Sigurd Hansen', 'male', 25.0, 0, 0, '348123', 7.65, 'F G73', 'S', 6.579000000000001], [77, 0, 3, 'Staneff, Mr. Ivan', 'male', nan, 0, 0, '349208', 7.8958, nan, 'S', 6.790388], [78, 0, 3, 'Moutal, Mr. Rahamin Haim', 'male', nan, 0, 0, '374746', 8.05, nan, 'S', 6.923000000000001], [79, 1, 2, 'Caldwell, Master Alden Gates', 'male', 0.83, 0, 2, '248738', 29.0, nan, 'S', 24.94], [80, 1, 3, 'Dowdell, Miss Elizabeth', 'female', 30.0, 0, 0, '364516', 12.475, nan, 'S', 10.7285], [81, 0, 3, 'Waelens, Mr. Achille', 'male', 22.0, 0, 0, '345767', 9.0, nan, 'S', 7.74], [82, 1, 3, 'Sheerlinck, Mr. Jan Baptist', 'male', 29.0, 0, 0, '345779', 9.5, nan, 'S', 8.17], [83, 1, 3, 'McDermott, Miss Brigdet Delia', 'female', nan, 0, 0, '330932', 7.7875, nan, 'Q', 6.6972499999999995], [84, 0, 1, 'Carrau, Mr. Francisco M', 'male', 28.0, 0, 0, '113059', 47.1, nan, 'S', 40.506], [85, 1, 2, 'Ilett, Miss Bertha', 'female', 17.0, 0, 0, 'SO/C 14885', 10.5, nan, 'S', 9.03], [86, 1, 3, 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 'female', 33.0, 3, 0, '3101278', 15.85, nan, 'S', 13.631], [87, 0, 3, 'Ford, Mr. William Neal', 'male', 16.0, 1, 3, 'W./C. 6608', 34.375, nan, 'S', 29.5625], [88, 0, 3, 'Slocovski, Mr. Selman Francis', 'male', nan, 0, 0, 'SOTON/OQ 392086', 8.05, nan, 'S', 6.923000000000001], [89, 1, 1, 'Fortune, Miss Mabel Helen', 'female', 23.0, 3, 2, '19950', 263.0, 'C23 C25 C27', 'S', 226.18], [90, 0, 3, 'Celotti, Mr. Francesco', 'male', 24.0, 0, 0, '343275', 8.05, nan, 'S', 6.923000000000001], [91, 0, 3, 'Christmann, Mr. Emil', 'male', 29.0, 0, 0, '343276', 8.05, nan, 'S', 6.923000000000001], [92, 0, 3, 'Andreasson, Mr. Paul Edvin', 'male', 20.0, 0, 0, '347466', 7.8542, nan, 'S', 6.754612], [93, 0, 1, 'Chaffee, Mr. Herbert Fuller', 'male', 46.0, 1, 0, 'W.E.P. 5734', 61.175, 'E31', 'S', 52.610499999999995], [94, 0, 3, 'Dean, Mr. Bertram Frank', 'male', 26.0, 1, 2, 'C.A. 2315', 20.575, nan, 'S', 17.694499999999998], [95, 0, 3, 'Coxon, Mr. Daniel', 'male', 59.0, 0, 0, '364500', 7.25, nan, 'S', 6.235], [96, 0, 3, 'Shorney, Mr. Charles Joseph', 'male', nan, 0, 0, '374910', 8.05, nan, 'S', 6.923000000000001], [97, 0, 1, 'Goldschmidt, Mr. George B', 'male', 71.0, 0, 0, 'PC 17754', 34.6542, 'A5', 'C', 29.802612000000003], [98, 1, 1, 'Greenfield, Mr. William Bertram', 'male', 23.0, 0, 1, 'PC 17759', 63.3583, 'D10 D12', 'C', 54.488138], [99, 1, 2, 'Doling, Mrs. John T (Ada Julia Bone)', 'female', 34.0, 0, 1, '231919', 23.0, nan, 'S', 19.78], [100, 0, 2, 'Kantor, Mr. Sinai', 'male', 34.0, 1, 0, '244367', 26.0, nan, 'S', 22.36], [101, 0, 3, 'Petranec, Miss Matilda', 'female', 28.0, 0, 0, '349245', 7.8958, nan, 'S', 6.790388], [102, 0, 3, 'Petroff, Mr. Pastcho ("Pentcho")', 'male', nan, 0, 0, '349215', 7.8958, nan, 'S', 6.790388], [103, 0, 1, 'White, Mr. Richard Frasar', 'male', 21.0, 0, 1, '35281', 77.2875, 'D26', 'S', 66.46724999999999], [104, 0, 3, 'Johansson, Mr. Gustaf Joel', 'male', 33.0, 0, 0, '7540', 8.6542, nan, 'S', 7.442612], [105, 0, 3, 'Gustafsson, Mr. Anders Vilhelm', 'male', 37.0, 2, 0, '3101276', 7.925, nan, 'S', 6.8155], [106, 0, 3, 'Mionoff, Mr. Stoytcho', 'male', 28.0, 0, 0, '349207', 7.8958, nan, 'S', 6.790388], [107, 1, 3, 'Salkjelsvik, Miss Anna Kristine', 'female', 21.0, 0, 0, '343120', 7.65, nan, 'S', 6.579000000000001], [108, 1, 3, 'Moss, Mr. Albert Johan', 'male', nan, 0, 0, '312991', 7.775, nan, 'S', 6.6865000000000006], [109, 0, 3, 'Rekic, Mr. Tido', 'male', 38.0, 0, 0, '349249', 7.8958, nan, 'S', 6.790388], [110, 1, 3, 'Moran, Miss Bertha', 'female', nan, 1, 0, '371110', 24.15, nan, 'Q', 20.769], [111, 0, 1, 'Porter, Mr. Walter Chamberlain', 'male', 47.0, 0, 0, '110465', 52.0, 'C110', 'S', 44.72], [112, 0, 3, 'Zabour, Miss Hileni', 'female', 14.5, 1, 0, '2665', 14.4542, nan, 'C', 12.430612], [113, 0, 3, 'Barton, Mr. David John', 'male', 22.0, 0, 0, '324669', 8.05, nan, 'S', 6.923000000000001], [114, 0, 3, 'Jussila, Miss Katriina', 'female', 20.0, 1, 0, '4136', 9.825, nan, 'S', 8.449499999999999], [115, 0, 3, 'Attalah, Miss Malake', 'female', 17.0, 0, 0, '2627', 14.4583, nan, 'C', 12.434137999999999], [116, 0, 3, 'Pekoniemi, Mr. Edvard', 'male', 21.0, 0, 0, 'STON/O 2. 3101294', 7.925, nan, 'S', 6.8155], [117, 0, 3, 'Connors, Mr. Patrick', 'male', 70.5, 0, 0, '370369', 7.75, nan, 'Q', 6.665], [118, 0, 2, 'Turpin, Mr. William John Robert', 'male', 29.0, 1, 0, '11668', 21.0, nan, 'S', 18.06], [119, 0, 1, 'Baxter, Mr. Quigg Edmond', 'male', 24.0, 0, 1, 'PC 17558', 247.5208, 'B58 B60', 'C', 212.867888], [120, 0, 3, 'Andersson, Miss Ellis Anna Maria', 'female', 2.0, 4, 2, '347082', 31.275, nan, 'S', 26.8965], [121, 0, 2, 'Hickman, Mr. Stanley George', 'male', 21.0, 2, 0, 'S.O.C. 14879', 73.5, nan, 'S', 63.21], [122, 0, 3, 'Moore, Mr. Leonard Charles', 'male', nan, 0, 0, 'A4. 54510', 8.05, nan, 'S', 6.923000000000001], [123, 0, 2, 'Nasser, Mr. Nicholas', 'male', 32.5, 1, 0, '237736', 30.0708, nan, 'C', 25.860888], [124, 1, 2, 'Webber, Miss Susan', 'female', 32.5, 0, 0, '27267', 13.0, 'E101', 'S', 11.18], [125, 0, 1, 'White, Mr. Percival Wayland', 'male', 54.0, 0, 1, '35281', 77.2875, 'D26', 'S', 66.46724999999999], [126, 1, 3, 'Nicola-Yarred, Master Elias', 'male', 12.0, 1, 0, '2651', 11.2417, nan, 'C', 9.667862], [127, 0, 3, 'McMahon, Mr. Martin', 'male', nan, 0, 0, '370372', 7.75, nan, 'Q', 6.665], [128, 1, 3, 'Madsen, Mr. Fridtjof Arne', 'male', 24.0, 0, 0, 'C 17369', 7.1417, nan, 'S', 6.141862], [129, 1, 3, 'Peter, Miss Anna', 'female', nan, 1, 1, '2668', 22.3583, 'F E69', 'C', 19.228138], [130, 0, 3, 'Ekstrom, Mr. Johan', 'male', 45.0, 0, 0, '347061', 6.975, nan, 'S', 5.9985], [131, 0, 3, 'Drazenoic, Mr. Jozef', 'male', 33.0, 0, 0, '349241', 7.8958, nan, 'C', 6.790388], [132, 0, 3, 'Coelho, Mr. Domingos Fernandeo', 'male', 20.0, 0, 0, 'SOTON/O.Q. 3101307', 7.05, nan, 'S', 6.063], [133, 0, 3, 'Robins, Mrs. Alexander A (Grace Charity Laury)', 'female', 47.0, 1, 0, 'A/5. 3337', 14.5, nan, 'S', 12.47], [134, 1, 2, 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 'female', 29.0, 1, 0, '228414', 26.0, nan, 'S', 22.36], [135, 0, 2, 'Sobey, Mr. Samuel James Hayden', 'male', 25.0, 0, 0, 'C.A. 29178', 13.0, nan, 'S', 11.18], [136, 0, 2, 'Richard, Mr. Emile', 'male', 23.0, 0, 0, 'SC/PARIS 2133', 15.0458, nan, 'C', 12.939388], [137, 1, 1, 'Newsom, Miss Helen Monypeny', 'female', 19.0, 0, 2, '11752', 26.2833, 'D47', 'S', 22.603638], [138, 0, 1, 'Futrelle, Mr. Jacques Heath', 'male', 37.0, 1, 0, '113803', 53.1, 'C123', 'S', 45.666000000000004], [139, 0, 3, 'Osen, Mr. Olaf Elon', 'male', 16.0, 0, 0, '7534', 9.2167, nan, 'S', 7.926361999999999], [140, 0, 1, 'Giglio, Mr. Victor', 'male', 24.0, 0, 0, 'PC 17593', 79.2, 'B86', 'C', 68.112], [141, 0, 3, 'Boulos, Mrs. Joseph (Sultana)', 'female', nan, 0, 2, '2678', 15.2458, nan, 'C', 13.111388], [142, 1, 3, 'Nysten, Miss Anna Sofia', 'female', 22.0, 0, 0, '347081', 7.75, nan, 'S', 6.665], [143, 1, 3, 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', 'female', 24.0, 1, 0, 'STON/O2. 3101279', 15.85, nan, 'S', 13.631], [144, 0, 3, 'Burke, Mr. Jeremiah', 'male', 19.0, 0, 0, '365222', 6.75, nan, 'Q', 5.805], [145, 0, 2, 'Andrew, Mr. Edgardo Samuel', 'male', 18.0, 0, 0, '231945', 11.5, nan, 'S', 9.89], [146, 0, 2, 'Nicholls, Mr. Joseph Charles', 'male', 19.0, 1, 1, 'C.A. 33112', 36.75, nan, 'S', 31.605], [147, 1, 3, 'Andersson, Mr. August Edvard ("Wennerstrom")', 'male', 27.0, 0, 0, '350043', 7.7958, nan, 'S', 6.704388], [148, 0, 3, 'Ford, Miss Robina Maggie "Ruby"', 'female', 9.0, 2, 2, 'W./C. 6608', 34.375, nan, 'S', 29.5625], [149, 0, 2, 'Navratil, Mr. Michel ("Louis M Hoffman")', 'male', 36.5, 0, 2, '230080', 26.0, 'F2', 'S', 22.36], [150, 0, 2, 'Byles, Rev. Thomas Roussel Davids', 'male', 42.0, 0, 0, '244310', 13.0, nan, 'S', 11.18], [151, 0, 2, 'Bateman, Rev. Robert James', 'male', 51.0, 0, 0, 'S.O.P. 1166', 12.525, nan, 'S', 10.7715], [152, 1, 1, 'Pears, Mrs. Thomas (Edith Wearne)', 'female', 22.0, 1, 0, '113776', 66.6, 'C2', 'S', 57.275999999999996], [153, 0, 3, 'Meo, Mr. Alfonzo', 'male', 55.5, 0, 0, 'A.5. 11206', 8.05, nan, 'S', 6.923000000000001], [154, 0, 3, 'van Billiard, Mr. Austin Blyler', 'male', 40.5, 0, 2, 'A/5. 851', 14.5, nan, 'S', 12.47], [155, 0, 3, 'Olsen, Mr. Ole Martin', 'male', nan, 0, 0, 'Fa 265302', 7.3125, nan, 'S', 6.28875], [156, 0, 1, 'Williams, Mr. Charles Duane', 'male', 51.0, 0, 1, 'PC 17597', 61.3792, nan, 'C', 52.786111999999996], [157, 1, 3, 'Gilnagh, Miss Katherine "Katie"', 'female', 16.0, 0, 0, '35851', 7.7333, nan, 'Q', 6.650638], [158, 0, 3, 'Corn, Mr. Harry', 'male', 30.0, 0, 0, 'SOTON/OQ 392090', 8.05, nan, 'S', 6.923000000000001], [159, 0, 3, 'Smiljanic, Mr. Mile', 'male', nan, 0, 0, '315037', 8.6625, nan, 'S', 7.44975], [160, 0, 3, 'Sage, Master Thomas Henry', 'male', nan, 8, 2, 'CA. 2343', 69.55, nan, 'S', 59.812999999999995], [161, 0, 3, 'Cribb, Mr. John Hatfield', 'male', 44.0, 0, 1, '371362', 16.1, nan, 'S', 13.846000000000002], [162, 1, 2, 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)', 'female', 40.0, 0, 0, 'C.A. 33595', 15.75, nan, 'S', 13.545], [163, 0, 3, 'Bengtsson, Mr. John Viktor', 'male', 26.0, 0, 0, '347068', 7.775, nan, 'S', 6.6865000000000006], [164, 0, 3, 'Calic, Mr. Jovo', 'male', 17.0, 0, 0, '315093', 8.6625, nan, 'S', 7.44975], [165, 0, 3, 'Panula, Master Eino Viljami', 'male', 1.0, 4, 1, '3101295', 39.6875, nan, 'S', 34.13125], [166, 1, 3, 'Goldsmith, Master Frank John William "Frankie"', 'male', 9.0, 0, 2, '363291', 20.525, nan, 'S', 17.6515], [167, 1, 1, 'Chibnall, Mrs. (Edith Martha Bowerman)', 'female', nan, 0, 1, '113505', 55.0, 'E33', 'S', 47.3], [168, 0, 3, 'Skoog, Mrs. William (Anna Bernhardina Karlsson)', 'female', 45.0, 1, 4, '347088', 27.9, nan, 'S', 23.994], [169, 0, 1, 'Baumann, Mr. John D', 'male', nan, 0, 0, 'PC 17318', 25.925, nan, 'S', 22.2955], [170, 0, 3, 'Ling, Mr. Lee', 'male', 28.0, 0, 0, '1601', 56.4958, nan, 'S', 48.586388], [171, 0, 1, 'Van der hoef, Mr. Wyckoff', 'male', 61.0, 0, 0, '111240', 33.5, 'B19', 'S', 28.81], [172, 0, 3, 'Rice, Master Arthur', 'male', 4.0, 4, 1, '382652', 29.125, nan, 'Q', 25.0475], [173, 1, 3, 'Johnson, Miss Eleanor Ileen', 'female', 1.0, 1, 1, '347742', 11.1333, nan, 'S', 9.574638], [174, 0, 3, 'Sivola, Mr. Antti Wilhelm', 'male', 21.0, 0, 0, 'STON/O 2. 3101280', 7.925, nan, 'S', 6.8155], [175, 0, 1, 'Smith, Mr. James Clinch', 'male', 56.0, 0, 0, '17764', 30.6958, 'A7', 'C', 26.398387999999997], [176, 0, 3, 'Klasen, Mr. Klas Albin', 'male', 18.0, 1, 1, '350404', 7.8542, nan, 'S', 6.754612], [177, 0, 3, 'Lefebre, Master Henry Forbes', 'male', nan, 3, 1, '4133', 25.4667, nan, 'S', 21.901362], [178, 0, 1, 'Isham, Miss Ann Elizabeth', 'female', 50.0, 0, 0, 'PC 17595', 28.7125, 'C49', 'C', 24.692749999999997], [179, 0, 2, 'Hale, Mr. Reginald', 'male', 30.0, 0, 0, '250653', 13.0, nan, 'S', 11.18], [180, 0, 3, 'Leonard, Mr. Lionel', 'male', 36.0, 0, 0, 'LINE', 0.0, nan, 'S', 0.0], [181, 0, 3, 'Sage, Miss Constance Gladys', 'female', nan, 8, 2, 'CA. 2343', 69.55, nan, 'S', 59.812999999999995], [182, 0, 2, 'Pernot, Mr. Rene', 'male', nan, 0, 0, 'SC/PARIS 2131', 15.05, nan, 'C', 12.943], [183, 0, 3, 'Asplund, Master Clarence Gustaf Hugo', 'male', 9.0, 4, 2, '347077', 31.3875, nan, 'S', 26.99325], [184, 1, 2, 'Becker, Master Richard F', 'male', 1.0, 2, 1, '230136', 39.0, 'F4', 'S', 33.54], [185, 1, 3, 'Kink-Heilmann, Miss Luise Gretchen', 'female', 4.0, 0, 2, '315153', 22.025, nan, 'S', 18.941499999999998], [186, 0, 1, 'Rood, Mr. Hugh Roscoe', 'male', nan, 0, 0, '113767', 50.0, 'A32', 'S', 43.0], [187, 1, 3, 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)', 'female', nan, 1, 0, '370365', 15.5, nan, 'Q', 13.33], [188, 1, 1, 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 'male', 45.0, 0, 0, '111428', 26.55, nan, 'S', 22.833000000000002], [189, 0, 3, 'Bourke, Mr. John', 'male', 40.0, 1, 1, '364849', 15.5, nan, 'Q', 13.33], [190, 0, 3, 'Turcin, Mr. Stjepan', 'male', 36.0, 0, 0, '349247', 7.8958, nan, 'S', 6.790388], [191, 1, 2, 'Pinsky, Mrs. (Rosa)', 'female', 32.0, 0, 0, '234604', 13.0, nan, 'S', 11.18], [192, 0, 2, 'Carbines, Mr. William', 'male', 19.0, 0, 0, '28424', 13.0, nan, 'S', 11.18], [193, 1, 3, 'Andersen-Jensen, Miss Carla Christine Nielsi

### Runtimes (in seconds)

(Referenced https://www.geeksforgeeks.org/python/python-measure-time-taken-by-program-to-execute/) for tracking time
2: pandas = 0.006998777389526367 Python = 0.0010323524475097656
3: pandas = 0.0009999275207519531 Python = 0.0010006427764892578
5: pandas = 0.0010008811950683594 Python = 0.0019986629486083984

It seems that pandas is overall faster at running my solutions to the questions than the pure Python I used.